### ISSUE TITLE
Cant access classroom discussion 

### ISSUE THREAD

**Issue by louisacql** [yale-mgt-858-spring-2023/.github#1]
Hi Kyle, After accepting your email invite, I still cannot access the "[classroom discussion](https://github.com/orgs/yale-mgt-858-spring-2023/discussions)" page

**Comment by kljensen** [comment]
You should be able to now @louisacql . You're on the "students" team and that team has read/write access to https://github.com/yale-mgt-858-spring-2023/discussions which is where the discussion at https://github.com/orgs/yale-mgt-858-spring-2023/discussions is stored.
